on: 
  push:
    branches: 
      - master
    tags:
      - '1.0'
name: Test Test B
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "lib/main.dart"
        bodyFile: "lib/weather/theme.dart"
        token: ${{ secrets.GITHUB_TOKEN }}
